spring.application.name=customer
spring.profiles.active=dev

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=


crm.welcome-message=Welcome to the Pro Spring Boot 4 CRM!
crm.max-results=50